# Generated by Django 5.2.11 on 2026-02-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_canvas_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chunk',
            new_name='directory_c_tsv_29df4d_gin',
            old_name='directory_c_tsv_gin',
        ),
    ]
