# Generated by Django 5.2.11 on 2026-02-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_canvassubaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvassubaccount',
            name='last_issued_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='canvassubaccount',
            name='last_password_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
