# Generated by Django 5.2.11 on 2026-02-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_canvassubaccount_last_issued_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvassubaccount',
            name='last_issued_password',
        ),
        migrations.RemoveField(
            model_name='canvassubaccount',
            name='last_password_issued_at',
        ),
    ]
